# This is a basic workflow to help you get started with Actions

name: Test Kitchen

on:
  push:
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  
jobs:
  Setup-ChefWorkstation:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checking if installation required
        continue-on-error: true
        id: check
        run: sudo dpkg -l | grep chef
      - name: Installing ChefWorkstation v21.2.278
        if: steps.check.outcome == 'failure'
        run: |
          wget -q https://packages.chef.io/files/stable/chef-workstation/21.2.278/ubuntu/20.04/chef-workstation_21.2.278-1_amd64.deb
          sudo dpkg -i chef-workstation_21.2.278-1_amd64.deb
          chef -v
  
  Setup-Docker:
    runs-on: self-hosted
    steps:
      - name: Checking if installation required
        continue-on-error: true
        id: check
        run: docker -v
      - name: Download and Install Docker
        if: steps.check.outcome == 'failure'
        run: |
          sudo apt update -y
          sudo apt install -y apt-transport-https ca-certificates curl gnupg lsb-release
          sudo apt install -y docker-compose
          docker -v
          sudo service docker start
          service docker status

  Test-Kitchen:
    runs-on: self-hosted
    needs: [ Setup-Docker, Setup-ChefWorkstation ]
    steps:
      - name: Run kitchen test
        run: |
          kitchen test
